WITH BOOK_SALED AS (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = '2022-01'
    GROUP BY BOOK_ID
), TOTAL_SALES AS (
    SELECT BOOK.BOOK_ID, CATEGORY, AUTHOR_ID, SUM(PRICE * BOOK_SALED.SALES) AS TOTAL_SALES
    FROM BOOK_SALED JOIN BOOK ON BOOK_SALED.BOOK_ID = BOOK.BOOK_ID
    GROUP BY AUTHOR_ID, CATEGORY
)
# SELECT * FROM TOTAL_SALES

SELECT A.AUTHOR_ID,	AUTHOR_NAME, CATEGORY, TOTAL_SALES
FROM TOTAL_SALES T JOIN AUTHOR A ON T.AUTHOR_ID = A.AUTHOR_ID
# GROUP BY A.AUTHOR_ID
ORDER BY 1 ASC, 3 DESC