WITH S_CAR_TYPE AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE IN ('세단', 'SUV')
), AVAILABLE_DATE AS (
    SELECT *
    FROM S_CAR_TYPE
    WHERE CAR_ID NOT IN (
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
), ANSWER AS (
    SELECT C.CAR_ID, C.CAR_TYPE, TRUNCATE(C.DAILY_FEE*30*(100 - IF(D.DURATION_TYPE = '90일 이상', 0, D.DISCOUNT_RATE))/100, 0) AS FEE
    FROM S_CAR_TYPE C
    JOIN AVAILABLE_DATE A ON C.CAR_ID = A.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE
    WHERE D.DURATION_TYPE = '30일 이상'
)
SELECT * FROM ANSWER
WHERE FEE BETWEEN 500000 AND 2000000-1
ORDER BY 3 DESC, 2 ASC, 1 DESC
