WITH CAR_WITH_OPTIONS AS(
    SELECT * 
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE OPTIONS LIKE '%통풍시트%' OR OPTIONS LIKE '%열선시트%' OR OPTIONS LIKE '%가죽시트%'
)


SELECT CAR_TYPE, COUNT(OPTIONS) AS CARS
FROM CAR_WITH_OPTIONS
GROUP BY CAR_TYPE
ORDER BY 1
