WITH COUNT_FISH AS (
    SELECT FISH_TYPE, COUNT(*) AS FISH_COUNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT C.FISH_COUNT, F.FISH_NAME
FROM FISH_NAME_INFO F RIGHT OUTER JOIN COUNT_FISH C ON F.FISH_TYPE = C.FISH_TYPE
ORDER BY 1 DESC;