WITH CAR AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
    GROUP BY CAR_ID
), HISTORY AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
    # GROUP BY CAR_ID
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
)

SELECT C.CAR_ID, IF(EXISTS(SELECT H.CAR_ID FROM HISTORY H WHERE C.CAR_ID = H.CAR_ID), '대여중', '대여 가능')
FROM CAR C
GROUP BY C.CAR_ID
ORDER BY 1 DESC