WITH UNCANCELED_APPOINTMENT AS (
    SELECT *
    FROM APPOINTMENT
    WHERE DATE_FORMAT(APNT_YMD, "%Y-%m-%d") = '2022-04-13' AND APNT_CNCL_YN = 'N'
        AND MCDP_CD = 'CS'
)

SELECT UA.APNT_NO AS APNT_NO, P.PT_NAME AS PT_NAME, P.PT_NO, UA.MCDP_CD, D.DR_NAME, UA.APNT_YMD
FROM UNCANCELED_APPOINTMENT UA, PATIENT P, DOCTOR D
WHERE UA.PT_NO = P.PT_NO AND UA.MDDR_ID = D.DR_ID
ORDER BY 6