WITH SUM_TRANSCATION AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES>=700000
)
SELECT U.USER_ID, U.NICKNAME, S.TOTAL_SALES
FROM USED_GOODS_USER U JOIN SUM_TRANSCATION S ON U.USER_ID = S.WRITER_ID
ORDER BY TOTAL_SALES