WITH CUSTOM_ECOLI AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY 1
)

select YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) AS YEAR , MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV, ECOLI_DATA.ID
from ECOLI_DATA JOIN CUSTOM_ECOLI AS M ON YEAR(ECOLI_DATA.DIFFERENTIATION_DATE)  = M.YEAR
ORDER BY 1, 2