WITH FIND_CAR AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
)
SELECT DISTINCT CAR_ID 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE) = 10 AND
    CAR_ID IN (SELECT CAR_ID FROM FIND_CAR)
ORDER BY 1 DESC