WITH FOOD AS (
    SELECT * 
    FROM FOOD_PRODUCT
    WHERE CATEGORY LIKE '과자' || CATEGORY LIKE '국' || 
        CATEGORY LIKE '김치' || CATEGORY LIKE '식용유'
), MAX_PRICE AS (
    SELECT CATEGORY, MAX(PRICE) AS MAXIMUM
    FROM FOOD
    GROUP BY CATEGORY
)

SELECT M.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM MAX_PRICE M JOIN FOOD_PRODUCT F ON M.CATEGORY = F.CATEGORY
WHERE M.MAXIMUM = F.PRICE
ORDER BY 2 DESC

# SELECT * FROM FOOD_PRODUCT